<?php

namespace AppBundle\Repository;

/**
 * BijouxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BijouxRepository extends \Doctrine\ORM\EntityRepository
{
    public function Bijouxretard()
    {
            
            $queryBuilder = $this->createQueryBuilder('b')
                    ->where('b.datefinprevu < b.datefin ');
                    
              //la requète des bijoux en retard

              // On récupère la Query à partir du QueryBuilder
              $query = $queryBuilder->getQuery();

              // On récupère les résultats à partir de la Query
              $results = $query->getResult();

              // On retourne ces résultats
              return $results;
    }
}
