<?php

namespace AppBundle\Repository;

/**
 * IncidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidentRepository extends \Doctrine\ORM\EntityRepository
{
    
}
