<?php

namespace AppBundle\Repository;

/**
 * TacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheRepository extends \Doctrine\ORM\EntityRepository
{
    
        public function findTacheVal($user_id)
    {
            
            $queryBuilder = $this->createQueryBuilder('t')
                    ->leftJoin('t.user', 'u')
                    ->where('u.id = :user_id')
                    ->setParameter('user_id', $user_id)
                    ->andWhere('t.datedebut is not null')
                    ->andWhere('t.datefin is null');
              // On n'ajoute pas de critère ou tri particulier, la construction
              // de notre requête est finie

              // On récupère la Query à partir du QueryBuilder
              $query = $queryBuilder->getQuery();

              // On récupère les résultats à partir de la Query
              $results = $query->getResult();

              // On retourne ces résultats
              return $results;
    }
}
